remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme

title: Nuevas Tecnologias

nombres: Sergio Daniel Marenco Cerpa
submodulo: Nuevas Tecnologias
descripcion: Aqui encontraras las envidencias/Entregables del submodulo Nuevas Tecnologias.
